- hosts: all
  vars:
    - git_vendor_path: "{{ lookup('env', 'DOTFILES_ROOT') }}/vendor"
  tasks:
    - name: install git modules
      git:
        accept_hostkey: yes
        dest: "{{ git_vendor_path }}/{{ item | basename | regex_replace('[.]git$', '') }}"
        repo: "{{ item.repo }}"
        update: yes
        notify: "{{ item.notify }}"
      with_items:
        - repo: git://github.com/rupa/z
          notify: install z
        - repo: git://github.com/tj/git-extras.git
          notify: install git-extras
        - repo: git://github.com/petdance/ack2.git
          notify: install ack

